# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-newlines-vars
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "test-newlines.name" . }}
data:
  test-newlines.ini: "{{ .Values.configFile }}"
  test-newlines.conf: |
    an alligator
    and another animal

    become 
    basically beaten

    
    cause cicrcles
    can't cure consussion
